import { fmt, fmt1, fmtN } from './formatters';
import { formulaRegistry } from './formulas';

const roundFmt = (value) =>
  !Number.isFinite(value) || Number.isNaN(value) ? '-' : `${value.toFixed(1)}`;

function createMeta(meta) {
  return {
    unit: '',
    fmt,
    tip: '',
    prefix: '',
    sticker: '',
    suffix: '',
    cfmt: '',
    ...meta,
  };
}

const metricDefinitions = {
  salePrice: createMeta({
    label: '회원권 분양가',
    unit: '만원',
    tip: '회원권 1건의 분양 금액',
  }),
  annualFee: createMeta({
    label: '연회비',
    prefix: '연간',
    unit: '만원',
    tip: '회원이 매년 납부하는 연회비',
  }),
  annualFixedProfit: createMeta({
    label: '기타 고정 손익',
    prefix: '연간',
    unit: '만원',
    tip: '회원권 및 라운딩 여부와 무관하게 회사에 연간 반복 발생하는 고정 손익(음수 입력 가능)',
  }),
  contractYears: createMeta({
    label: '계약기간',
    unit: '년',
    fmt: fmtN,
    tip: '회원권 계약 기간',
  }),
  yearlyChurnRate: createMeta({
    label: '해지율',
    unit: '%',
    fmt: fmt1,
    sticker: '예측치',
    tip: '각 연도 종료 시점 기준 해지 비율의 기대값',
  }),
  yearlyRefundAmount: createMeta({
    label: '회원권 해지 환불금',
    unit: '만원',
    fmt: fmt1,
    tip: '각 연도 종료 시점 기준 해지 시 1인당 일괄 지급되는 환불금',
  }),
  roundLimitByRegion: createMeta({
    label: '연간 라운딩 한도',
    unit: '회',
    fmt: fmtN,
    tip: '연간 최대 라운딩 수',
  }),
  yearlyUsageRateByRegion: createMeta({
    label: '연간 이용률',
    unit: '%',
    fmt: fmt1,
    sticker: '예측치',
    tip: '연도별 이용률',
  }),
  courseCostByRegion: createMeta({
    label: '구장 매입가(B2B)',
    unit: '만원',
    fmt: fmt1,
    tip: '구장과 계약을 통해 회사에서 매입하는 단가입니다.(기타 비용 포함)',
  }),
  memberPriceByRegion: createMeta({
    label: '회원 판매가',
    unit: '만원',
    fmt: fmt1,
    tip: '기명/무기명 회원 1인당 판매 단가',
  }),
  membersByRegion: createMeta({
    label: '라운딩당 평균 회원 수',
    unit: '명',
    fmt: fmt1,
    sticker: '예측치',
    tip: '라운딩당 기명/무기명 회원 평균 인원 수',
  }),
  companionPriceByRegion: createMeta({
    label: '동반 비회원 판매가',
    unit: '만원',
    fmt: fmt1,
    tip: '비회원 동반 1인당 판매 단가',
  }),
  companionsByRegion: createMeta({
    label: '라운딩당 평균 동반 수',
    unit: '명',
    fmt: fmt1,
    sticker: '예측치',
    tip: '라운딩당 동반 비회원 평균 인원 수',
  }),
  publicPriceByRegion: createMeta({
    label: '구장 일반 판매가(B2C)',
    unit: '만원',
    fmt: fmt1,
    tip: '구장에서 일반 고객에 직접 판매하는 단가',
  }),
  totalRoundLimit: createMeta({
    label: '연간 라운딩 한도',
    unit: '회',
    fmt: fmtN,
    prefix: '합계',
    tip: '전체 지역 연간 라운딩 한도 합계',
    formula: formulaRegistry.totalRoundLimit,
  }),
  weightedUsageRate: createMeta({
    label: '연간 이용률',
    unit: '%',
    fmt: fmt1,
    prefix: '평균',
    sticker: '예측치',
    tip: '전체 지역 연간 이용률 가중 평균',
    formula: formulaRegistry.weightedUsageRate,
  }),
  weightedCourseCost: createMeta({
    label: '구장 매입가',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '전체 지역 구장 매입가 가중 평균',
    formula: formulaRegistry.weightedCourseCost,
  }),
  weightedMemberPrice: createMeta({
    label: '회원 판매가',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '전체 지역 회원 판매가 가중 평균',
    formula: formulaRegistry.weightedMemberPrice,
  }),
  weightedMembers: createMeta({
    label: '라운딩당 평균 회원 수',
    unit: '명',
    fmt: fmt1,
    prefix: '평균',
    sticker: '예측치',
    tip: '라운딩당 기명/무기명 회원 평균 인원 수',
    formula: formulaRegistry.weightedMembers,
  }),
  weightedCompanionPrice: createMeta({
    label: '동반 판매가',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '전체 지역 동반 판매가 가중 평균',
    formula: formulaRegistry.weightedCompanionPrice,
  }),
  weightedCompanions: createMeta({
    label: '라운딩당 평균 동반 수',
    unit: '명',
    fmt: fmt1,
    prefix: '평균',
    sticker: '예측치',
    tip: '라운딩당 동반 비회원 평균 인원 수',
    formula: formulaRegistry.weightedCompanions,
  }),
  weightedPeoplePerRound: createMeta({
    label: '라운딩당 평균 총 인원 수',
    unit: '명',
    fmt: fmt1,
    prefix: '평균',
    sticker: '예측치',
    tip: '라운딩당 기명/무기명 회원 및 비회원 동반자를 합한 평균 인원 수',
    formula: formulaRegistry.weightedPeoplePerRound,
  }),
  peoplePerRoundByRegion: createMeta({
    label: '라운딩당 평균 인원 수',
    unit: '명',
    fmt: fmt1,
    sticker: '예측치',
    tip: '라운딩당 기명/무기명 회원 및 비회원 동반자를 합한 평균 인원 수',
    formula: formulaRegistry.peoplePerRoundByRegion,
  }),
  membersPerRoundByRegion: createMeta({
    label: '평균 회원 인원 수',
    unit: '명',
    fmt: fmt1,
    sticker: '예측치',
    tip: '라운딩당 기명/무기명 회원 인원 수 기대값',
    formula: formulaRegistry.membersPerRoundByRegion,
  }),
  companionsPerRoundByRegion: createMeta({
    label: '평균 동반 인원 수',
    unit: '명',
    fmt: fmt1,
    sticker: '예측치',
    tip: '라운딩당 동반 비회원 인원 수 기대값',
    formula: formulaRegistry.companionsPerRoundByRegion,
  }),
  weightedPublicPrice: createMeta({
    label: '구장 일반 판매가',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '전체 지역 일반 판매가 가중 평균',
    formula: formulaRegistry.weightedPublicPrice,
  }),
  actualRoundsByRegion: createMeta({
    label: '연간 라운딩 횟수',
    unit: '회',
    fmt: roundFmt,
    tip: '연간 라운딩 한도와 이용률을 곱한 값',
    formula: formulaRegistry.actualRoundsByRegion,
  }),
  totalActualRounds: createMeta({
    label: '연간 라운딩 횟수',
    unit: '회',
    fmt: roundFmt,
    prefix: '합계',
    tip: '전체 지역 연간 라운딩 횟수 합계',
    formula: formulaRegistry.totalActualRounds,
  }),
  weightByRegion: createMeta({
    label: '비중',
    unit: '%',
    fmt: fmtN,
    tip: '전체 라운딩 횟수 중 해당 지역 비중',
    formula: formulaRegistry.weightByRegion,
  }),
  totalWeightByRegion: createMeta({
    label: '총 비중',
    unit: '%',
    fmt: fmtN,
    prefix: '합계',
    tip: '전체 지역 비중 합계',
    formula: formulaRegistry.totalWeightByRegion,
  }),
  marginPerRoundByRegion: createMeta({
    label: '라운딩당 평균 손익',
    prefix: '평균',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'profit',
    tip: '회원 손익과 동반 손익의 합',
    formula: formulaRegistry.marginPerRoundByRegion,
  }),
  weightedMarginPerRound: createMeta({
    label: '라운딩당 평균 손익',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    cfmt: 'profit',
    tip: '라운딩당 평균 손익(회사 기준)',
    formula: formulaRegistry.weightedMarginPerRound,
  }),
  memberProfitByRegion: createMeta({
    label: '회원 손익',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'profit',
    tip: '회원 판매가와 매입가 차이에 회원 수를 곱한 값',
    formula: formulaRegistry.memberProfitByRegion,
  }),
  weightedMemberProfit: createMeta({
    label: '회원 손익',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    cfmt: 'profit',
    tip: '전체 지역 평균 회원 손익 가중 평균',
    formula: formulaRegistry.weightedMemberProfit,
  }),
  companionProfitByRegion: createMeta({
    label: '동반 손익',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'profit',
    tip: '동반 판매가와 매입가 차이에 동반 수를 곱한 값',
    formula: formulaRegistry.companionProfitByRegion,
  }),
  weightedCompanionProfit: createMeta({
    label: '동반 손익',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    cfmt: 'profit',
    tip: '전체 지역 동반 손익 가중 평균',
    formula: formulaRegistry.weightedCompanionProfit,
  }),
  memberSavingByRegion: createMeta({
    label: '회원 절감액',
    unit: '만원',
    fmt: fmt1,
    tip: '라운딩당 구장 일반(B2C) 판매가 대비 회원 할인 효과',
    formula: formulaRegistry.memberSavingByRegion,
  }),
  weightedMemberSaving: createMeta({
    label: '회원 절감액',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '실제 라운드 비중 기준 평균 회원 절감액',
    formula: formulaRegistry.weightedMemberSaving,
  }),
  companionSavingByRegion: createMeta({
    label: '동반 절감액',
    unit: '만원',
    fmt: fmt1,
    tip: '라운딩당 구장 일반(B2C) 판매가 대비 동반 할인 효과',
    formula: formulaRegistry.companionSavingByRegion,
  }),
  weightedCompanionSaving: createMeta({
    label: '동반 절감액',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '실제 라운드 비중 기준 평균 동반 절감액',
    formula: formulaRegistry.weightedCompanionSaving,
  }),
  annualRoundingByRegion: createMeta({
    label: '연간 라운딩 손익',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'profit',
    tip: '라운딩당 손익과 연간 라운딩 횟수의 곱',
    formula: formulaRegistry.annualRoundingByRegion,
  }),
  totalAnnualRounding: createMeta({
    label: '연간 라운딩 손익',
    unit: '만원',
    fmt: fmt1,
    prefix: '합계',
    cfmt: 'profit',
    tip: '전체 지역 연간 라운딩 손익 합계',
    formula: formulaRegistry.totalAnnualRounding,
  }),
  savingPerRoundByRegion: createMeta({
    label: '라운딩당 회원 절감액',
    unit: '만원',
    fmt: fmt1,
    tip: '라운딩당 구장 일반 판매가 대비 평균 절감액(회원 및 동반자)',
    formula: formulaRegistry.savingPerRoundByRegion,
  }),
  weightedSavingPerRound: createMeta({
    label: '라운딩당 회원 절감액',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '라운딩당 구장 일반 판매가 대비 평균 절감액(회원 및 동반자)',
    formula: formulaRegistry.weightedSavingPerRound,
  }),
  annualSavingByRegion: createMeta({
    label: '회원 연간 절감액',
    unit: '만원',
    fmt: fmt1,
    tip: '라운딩당 회원 절감액과 연간 라운딩 횟수의 곱',
    formula: formulaRegistry.annualSavingByRegion,
  }),
  totalAnnualSaving: createMeta({
    label: '회원 연간 절감액',
    unit: '만원',
    fmt: fmt1,
    prefix: '합계',
    tip: '전체 지역 회원 연간 절감액 합계',
    formula: formulaRegistry.totalAnnualSaving,
  }),
  naiveFixedProfit: createMeta({
    label: '만기 고정 손익',
    prefix: '총',
    unit: '만원',
    cfmt: 'profit',
    tip: '(만기 기준) 총 연회비 + 분양가 + 기타손익',
    formula: formulaRegistry.naiveFixedProfit,
  }),
  companyBEP: createMeta({
    label: '회사 BEP',
    fmt: fmtN,
    nullLabel: '마진 흑자 구간',
    prefix: '총',
    suffix: '회 미만',
    unit: '회 미만',
    tip: '회사 손익 발생 최대 라운딩 수',
    formula: formulaRegistry.companyBEP,
  }),
  customerBEP: createMeta({
    label: '회원 BEP',
    fmt: fmtN,
    prefix: '총',
    suffix: '회 이상',
    unit: '회 이상',
    tip: '회원 투자금 회수 최소 라운딩 수',
    formula: formulaRegistry.customerBEP,
  }),
  naiveCustomerFixedCost: createMeta({
    label: '만기 분양가 및 연회비',
    prefix: '총',
    unit: '만원',
    cfmt: 'cost',
    tip: '(만기 기준) 총 연회비 + 분양가',
    formula: formulaRegistry.naiveCustomerFixedCost,
  }),
  ltv: createMeta({
    label: 'LTV',
    unit: '만원',
    prefix: '총',
    cfmt: 'profit',
    tip: '회원권 1건의 Life Time Value',
    formula: formulaRegistry.ltv,
  }),
  avgAnnualProfit: createMeta({
    label: '연간 평균 손익',
    unit: '만원',
    cfmt: 'profit',
    tip: '계약기간 기준 연간 평균 손익',
    formula: formulaRegistry.avgAnnualProfit,
  }),
  avgAnnualVariableProfit: createMeta({
    label: '연간 손익',
    prefix: '평균',
    unit: '만원',
    cfmt: 'profit',
    tip: '연 평균 손익(회원권 분양/환불액 제외)',
    formula: formulaRegistry.avgAnnualVariableProfit,
  }),
  avgAnnualVariableRevenue: createMeta({
    label: '연간 매출',
    prefix: '평균',
    unit: '만원',
    cfmt: 'revenue',
    tip: '라운딩 매출 + 연회비 + 기타 고정 손익(+)',
    formula: formulaRegistry.avgAnnualVariableRevenue,
  }),
  avgAnnualVariableCost: createMeta({
    label: '연간 비용',
    prefix: '평균',
    unit: '만원',
    cfmt: 'cost',
    tip: '라운딩 비용 + 기타 고정 손익(-)',
    formula: formulaRegistry.avgAnnualVariableCost,
  }),
  expectedEnrollProfit: createMeta({
    label: '회원권 분양 기대 손익',
    prefix: '총',
    unit: '만원',
    cfmt: 'profit',
    tip: '회원권 분양가 - 해지 환불금 기대값',
    formula: formulaRegistry.expectedEnrollProfit,
  }),
  expectedMaturitySurvivingRate: createMeta({
    label: '만기 잔존률',
    unit: '%',
    fmt: fmt1,
    tip: '연차별 해지율 반영 기준 계약 만기 시점 기대 잔존률',
    formula: formulaRegistry.expectedMaturitySurvivingRate,
  }),
  avgAnnualRounds: createMeta({
    label: '연간 평균 라운딩 횟수',
    unit: '회',
    fmt: roundFmt,
    tip: '전체 지역 연간 평균 라운딩 횟수 합계',
    formula: formulaRegistry.avgAnnualRounds,
  }),
  customerNetProfit: createMeta({
    label: '회원 순이익',
    unit: '만원',
    cfmt: 'profit',
    tip: '회원 절감액 누적에서 분양가를 차감한 값',
    formula: formulaRegistry.customerNetProfit,
  }),
  avgChurnRate: createMeta({
    label: '해지율',
    unit: '%',
    fmt: fmt1,
    prefix: '연평균',
    sticker: '예측치',
    tip: '연도별 해지율 평균',
    formula: formulaRegistry.avgChurnRate,
  }),
  avgRefundAmount: createMeta({
    label: '연간 해지 환불금',
    unit: '만원',
    fmt: fmt1,
    prefix: '평균',
    tip: '연도별 해지 환불금 평균',
    formula: formulaRegistry.avgRefundAmount,
  }),
  avgUsageRateByRegion: createMeta({
    label: '연간 이용률',
    unit: '%',
    fmt: fmt1,
    sticker: '예측치',
    tip: '지역별 연간 이용률 평균',
    formula: formulaRegistry.avgUsageRateByRegion,
  }),

  enrollFeeAnnualValue: createMeta({ formula: formulaRegistry.enrollFeeAnnualValue }),
  annualFeeRevenueValue: createMeta({ formula: formulaRegistry.annualFeeRevenueValue }),
  annualFixedProfitValue: createMeta({ formula: formulaRegistry.annualFixedProfitValue }),
  annualTotalValue: createMeta({ formula: formulaRegistry.annualTotalValue }),
  totalExpectedAnnualFeeRevenue: createMeta({
    label: '총 기대 연회비 매출',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'revenue',
    tip: '연도별 연초 잔존 기준으로 합산한 총 기대 연회비 매출',
    formula: formulaRegistry.totalExpectedAnnualFeeRevenue,
  }),
  totalExpectedPositiveAnnualFixedProfit: createMeta({
    label: '총 기대 양수 고정 손익',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'revenue',
    tip: '연도별 연초 잔존 기준으로 합산한 양수 고정 손익 합계',
    formula: formulaRegistry.totalExpectedPositiveAnnualFixedProfit,
  }),
  totalExpectedNegativeAnnualFixedCost: createMeta({
    label: '총 기대 음수 고정 비용',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'cost',
    tip: '연도별 연초 잔존 기준으로 합산한 음수 고정 손익의 비용 합계',
    formula: formulaRegistry.totalExpectedNegativeAnnualFixedCost,
  }),
  totalExpectedRoundingRevenue: createMeta({
    label: '총 기대 라운딩 매출',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'revenue',
    tip: '연도별 사용률과 연초 잔존 기준으로 합산한 총 기대 라운딩 매출',
    formula: formulaRegistry.totalExpectedRoundingRevenue,
  }),
  totalExpectedRoundingCost: createMeta({
    label: '총 기대 라운딩 비용',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'cost',
    tip: '연도별 사용률과 연초 잔존 기준으로 합산한 총 기대 라운딩 비용',
    formula: formulaRegistry.totalExpectedRoundingCost,
  }),
  totalExpectedVariableRevenue: createMeta({
    label: '총 기대 변동 매출',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'revenue',
    tip: '총 기대 연회비 매출, 양수 고정 손익, 라운딩 매출의 합',
    formula: formulaRegistry.totalExpectedVariableRevenue,
  }),
  totalExpectedVariableCost: createMeta({
    label: '총 기대 변동 비용',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'cost',
    tip: '총 기대 음수 고정 비용과 라운딩 비용의 합',
    formula: formulaRegistry.totalExpectedVariableCost,
  }),
  totalExpectedRefundCost: createMeta({
    label: '해지 환불금',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'cost',
    tip: '연도별 해지율 x 환불금을 합산한 기대값',
    formula: formulaRegistry.totalExpectedRefundCost,
  }),
  yearWeightedUsageRate: createMeta({
    label: '연간 이용률',
    unit: '%',
    fmt: fmt1,
    tip: '연도별 라운딩 한도 가중 기준 평균 이용률',
    formula: formulaRegistry.yearWeightedUsageRate,
  }),
  yearChurnRate: createMeta({
    label: '연간 해지율',
    unit: '%',
    fmt: fmt1,
    tip: '해당 연말에 적용되는 해지율',
    formula: formulaRegistry.yearChurnRate,
  }),
  yearRefundAmount: createMeta({
    label: '연간 해지 환불금',
    unit: '만원',
    fmt: fmt1,
    tip: '해당 연말 해지 1인당 지급되는 환불금',
    formula: formulaRegistry.yearRefundAmount,
  }),
  yearEnrollFee: createMeta({
    label: '연간 분양가',
    unit: '만원',
    fmt: fmt1,
    tip: '첫 해에만 인식되는 분양가 손익',
    formula: formulaRegistry.yearEnrollFee,
  }),
  yearSurvivingEnd: createMeta({ formula: formulaRegistry.yearSurvivingEnd }),
  yearRefundCost: createMeta({
    label: '해지 환불금',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'cost',
    tip: '연말 해지 기준 환불금',
    formula: formulaRegistry.yearRefundCost,
  }),
  yearSurvivingStartRate: createMeta({
    label: '잔존률',
    unit: '%',
    fmt: fmt1,
    tip: '연초 기준 회원 기대 잔존률',
    formula: formulaRegistry.yearSurvivingStartRate,
  }),
  yearActualRoundsExpected: createMeta({
    label: '연간 라운딩 횟수',
    unit: '회',
    fmt: roundFmt,
    tip: '잔존률 및 이용률 반영 기준 연간 라운딩 횟수',
    formula: formulaRegistry.yearActualRoundsExpected,
  }),
  yearMemberRevenueExpected: createMeta({
    label: '연간 회원 판매가',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'revenue',
    tip: '잔존률 반영 기준 연간 회원 판매가',
    formula: formulaRegistry.yearMemberRevenueExpected,
  }),
  yearCompanionRevenueExpected: createMeta({
    label: '연간 동반 판매가',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'revenue',
    tip: '잔존률 반영 기준 연간 동반 판매가',
    formula: formulaRegistry.yearCompanionRevenueExpected,
  }),
  yearRoundingCostExpected: createMeta({
    label: '연간 매입가(B2B)',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'cost',
    tip: '잔존률 반영 기준 연간 매입가(B2B)',
    formula: formulaRegistry.yearRoundingCostExpected,
  }),
  yearRoundingRevenueExpected: createMeta({
    label: '라운딩 매출',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'revenue',
    tip: '연간 회원 판매가와 연간 동반 판매가의 합',
    formula: formulaRegistry.yearRoundingRevenueExpected,
  }),
  yearVariableProfitExpected: createMeta({
    label: '연간 변동 손익',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'profit',
    tip: '분양가, 연회비, 환불금을 제외한 연간 변동 손익',
    formula: formulaRegistry.yearVariableProfitExpected,
  }),
  yearCashFlowExpected: createMeta({
    label: '연간 현금 흐름',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'profit',
    tip: '분양가, 연회비, 해지 환불금, 변동 손익 기준 연간 현금 흐름',
    formula: formulaRegistry.yearCashFlowExpected,
  }),
  yearCumulativeLtv: createMeta({
    label: '누적 LTV',
    unit: '만원',
    fmt: fmt1,
    cfmt: 'profit',
    tip: '연차별 누적 LTV',
  }),
  yearRoundingRevenue: createMeta({ formula: formulaRegistry.yearRoundingRevenue }),
  yearRevenue: createMeta({ formula: formulaRegistry.yearRevenue }),
  yearFixedProfitValue: createMeta({ formula: formulaRegistry.yearFixedProfitValue }),
  sensitivityLtv: createMeta({ formula: formulaRegistry.sensitivityLtv }),
};

export const V = metricDefinitions;

export function fmtBEP(key, value, annual) {
  const meta = V[key];
  if (!meta || value == null || !Number.isFinite(value)) {
    return '-';
  }

  const baseValue = meta.fmt(value);
  const suffix = meta.suffix || '';
  return annual ? `연평균 ${baseValue}${suffix}` : `${baseValue}${suffix}`;
}
